# Dependabot configuration file
version: 2
updates:
  # Enable version updates for npm/yarn
  - package-ecosystem: "npm"
    # Look for package files in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check for updates on Monday
      day: "monday"
    # Group all updates into a single PR
    groups:
      dependencies:
        patterns:
          - "*"
    # Set reviewers for pull requests
    reviewers:
      - "quantikr"
    # Labels on pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Specify version update strategy
    versioning-strategy: increase
    # Set pull request limits
    open-pull-requests-limit: 10
    # Configure commit message
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
      - "automerge"
    commit-message:
      prefix: "ci"
      include: "scope"
