nodeLinker: node-modules

compressionLevel: mixed

enableGlobalCache: false

nmMode: hardlinks-local

networkConcurrency: 48

preferInteractive: true

defaultProtocol: "npm:"

pnpIgnorePatterns:
  - "**/node_modules/**"
