name = "next-new"
compatibility_date = "2024-01-01"

[build]
command = "yarn build"
output_directory = ".next"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".next"

[env.production]
name = "next-new-production"

[env.staging]
name = "next-new-staging"

# Add your environment variables here
# [vars]
# MY_VAR = "production_value"

# Staging environment variables
# [env.staging.vars]
# MY_VAR = "staging_value"
